# In terminal, run: conda env create -f environment.yml
# To update, run: conda env update -f environment.yml

name: marketing_mix_modelling

channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.1
  - pip
  - pip:
      # Core Data
      - numpy==1.20.2
      - pandas==1.2.2

      # Visualization
      - matplotlib==3.3.4
      - plotly==4.14.3
      - seaborn==0.11.2
      - nbformat

      # Modeling & Machine Learning
      - statsmodels
      - scikit-learn==0.23.2
      - xgboost==0.90
      - sklearn-pandas==2.0.4
      - scikit-misc==0.1.3

      # Joblib
      - joblib

      # Apps
      - dash==1.20.0
      - dash_bootstrap_components==0.12.2
      - dash_design_kit==0.0.1
      - dash_daq==0.5.0
      - werkzeug==2.0.3